all: 
	gcc -Wall -Werror process.c -o process 
	gcc -Wall -Werror process_vma.c -o process_vma
	gcc -Wall -Werror fork-01.c -o fork-01
	gcc -Wall -Werror fork-02.c -o fork-02

clean:
	rm process
	rm process_vma
	rm fork-01
	rm fork-02
